/**
 * Pure builder for `content/COVERAGE.md`. Deliberately has no time-varying
 * inputs (no timestamps) — its output is a pure function of the import
 * results, so re-running the importer with unchanged upstream data
 * produces a byte-identical file.
 */

export interface VersionCoverageStat {
  layer: 'source' | 'commentary'
  versionId: string
  chaptersTotal: number
  chaptersWithText: number
  segments: number
  /** Chapter ids that were attempted for this version but ended up with zero segments. */
  emptyChapterIds: string[]
}

export interface PartCoverage {
  partId: string
  partTitle: string
  stats: VersionCoverageStat[]
  warnings: string[]
}

const table = (stats: VersionCoverageStat[]): string => {
  const header = '| Layer | Version | Chapters w/ text | Chapters total | Segments |'
  const divider = '| --- | --- | --- | --- | --- |'
  const rows = stats.map(
    s => `| ${s.layer} | ${s.versionId} | ${s.chaptersWithText} | ${s.chaptersTotal} | ${s.segments} |`,
  )
  return [header, divider, ...rows].join('\n')
}

const emptyChapterNotes = (stats: VersionCoverageStat[]): string[] =>
  stats
    .filter(s => s.emptyChapterIds.length > 0)
    .map(s => `- **${s.layer}/${s.versionId}**: no text for ${s.emptyChapterIds.length} chapter(s) — ${s.emptyChapterIds.join(', ')}`)

export const buildCoverageMarkdown = (parts: PartCoverage[]): string => {
  const sections = parts.map((part) => {
    const lines = [`## ${part.partTitle} (\`${part.partId}\`)`, '', table(part.stats)]

    const notes = emptyChapterNotes(part.stats)
    if (notes.length > 0) {
      lines.push('', '**Empty-version chapters:**', ...notes)
    }

    if (part.warnings.length > 0) {
      lines.push('', '**Warnings:**', ...part.warnings.map(w => `- ${w}`))
    }

    return lines.join('\n')
  })

  return [
    '# Import coverage',
    '',
    'Generated by `pnpm import:sefaria`. Per part × layer × version: how many',
    'of the part\'s resolved chapters ended up with text in that version, and',
    'how many total segments/commentary items were written.',
    '',
    ...sections,
    '',
  ].join('\n')
}
