/**
 * Pure builder for `content/COVERAGE.md`. Deliberately has no time-varying
 * inputs (no timestamps) — its output is a pure function of the import
 * results, so re-running the importer with unchanged upstream data
 * produces a byte-identical file.
 */

export interface VersionCoverageStat {
  layer: "source" | "commentary";
  versionId: string;
  chaptersTotal: number;
  chaptersWithText: number;
  segments: number;
  /** Chapter ids that were attempted for this version but ended up with zero segments. */
  emptyChapterIds: string[];
}

export interface PartCoverage {
  partId: string;
  partTitle: string;
  stats: VersionCoverageStat[];
  warnings: string[];
  /**
   * How many `kind: "inner-observation"` chapters the part resolved to.
   * Zero is not an import failure — five parts have no Histaklut Pnimit to
   * import at all — so the report says so in the part's own section rather
   * than leaving a silently short table. Passed in rather than inferred
   * from `stats` (which are per layer × version, and Inner Observation is
   * carried by chapters, not by a layer of its own).
   */
  innerObservationChapters: number;
}

const table = (stats: VersionCoverageStat[]): string => {
  const header =
    "| Layer | Version | Chapters w/ text | Chapters total | Segments |";
  const divider = "| --- | --- | --- | --- | --- |";
  const rows = stats.map(
    (s) =>
      `| ${s.layer} | ${s.versionId} | ${s.chaptersWithText} | ${s.chaptersTotal} | ${s.segments} |`,
  );
  return [header, divider, ...rows].join("\n");
};

const emptyChapterNotes = (stats: VersionCoverageStat[]): string[] =>
  stats
    .filter((s) => s.emptyChapterIds.length > 0)
    .map(
      (s) =>
        `- **${s.layer}/${s.versionId}**: no text for ${s.emptyChapterIds.length} chapter(s) — ${s.emptyChapterIds.join(", ")}`,
    );

export const buildCoverageMarkdown = (parts: PartCoverage[]): string => {
  const sections = parts.map((part) => {
    const lines = [
      `## ${part.partTitle} (\`${part.partId}\`)`,
      "",
      table(part.stats),
    ];

    if (part.innerObservationChapters === 0) {
      lines.push(
        "",
        "**No Inner Observation (Histaklut Pnimit).** Baal HaSulam wrote none",
        "for this part; it is absent from the work, not from the import. See",
        '"Not written vs. not yet imported" above for the evidence and what it',
        "does and does not establish.",
      );
    }

    const notes = emptyChapterNotes(part.stats);
    if (notes.length > 0) {
      lines.push("", "**Empty-version chapters:**", ...notes);
    }

    if (part.warnings.length > 0) {
      lines.push("", "**Warnings:**", ...part.warnings.map((w) => `- ${w}`));
    }

    return lines.join("\n");
  });

  return [
    "# Import coverage",
    "",
    "Generated by `pnpm import:sefaria`. Per part × layer × version: how many",
    "of the part's resolved chapters ended up with text in that version, and",
    "how many total segments/commentary items were written.",
    "",
    "## Not written vs. not yet imported",
    "",
    "An empty row below is a gap in what has been *imported*. One absence in",
    "this corpus is not a gap at all — the text does not exist to import:",
    "",
    "- **Histaklut Pnimit (Inner Observation) — parts 5, 11, 14, 15 and 16",
    "  (2,193 of the corpus's 5,148 chapters): not written.** Baal HaSulam",
    "  wrote an Inner Observation for 11 of the 16 parts and none for these",
    "  five. Two structural sources carry the claim and a third corroborates",
    "  it (issue #80): Sefaria's index has a Histaklut node for the other",
    "  eleven Sections only, and Bnei Baruch's published contents listing",
    "  omits Inner Observation for exactly these five. The reader states this",
    "  as a fact about the work, not as pending work",
    "  (`reader.innerObservationNeverWritten`).",
    "- **Ohr Pnimi (Inner Light) — everything outside the 25 digitized",
    "  chapters: not yet imported.** This one *is* a digitization gap and",
    "  behaves like one — parts 1-4 and then nothing, a stopped tail rather",
    '  than holes — so its copy keeps the "yet"',
    "  (`reader.innerLightAbsent`).",
    "",
    "### The cross-reference evidence, and what it does not establish",
    "",
    "The corroborating third source is a census of Baal HaSulam's own",
    '`הסת"פ` / `הסתכלות פנימית` cross-references in `he-jerusalem-1956`,',
    "classified by whether a part qualifier sits beside them. Not one of them",
    "points at parts 5, 11, 14, 15 or 16 — from inside those parts or from any",
    "other part.",
    "",
    "**It corroborates but cannot prove.** Part 12 *has* an Inner Observation",
    "and still scores zero on both counters — no self-reference of its own,",
    "and nothing elsewhere in the corpus citing it — so a count of zero is",
    "demonstrably possible for a part that does have one. The census's value",
    "is that it is independent of both structural sources and agrees with them",
    "on all 16 parts, not that a silence proves an absence.",
    "",
    "**The signal is also not uniform across the five.** Parts 5, 11 and 14",
    "each contain exactly one Inner Observation reference and it is outbound,",
    "which is what an author does when the part at hand has none:",
    "`part-05/answers-topics-88` sends the reader to the end of part 1,",
    "`part-11/answers-topics-68` to part 2, `part-14/answers-topics-26` to",
    "part 13. Parts 15 and 16 contain no such reference at all, so they carry",
    "no qualitative signal either way.",
    "",
    ...sections,
    "",
  ].join("\n");
};
