/**
 * Coverage reporting for the KabbalahMedia importer, and the pure markdown
 * merge that lets it append/replace its own section of `content/COVERAGE.md`
 * without touching whatever `pnpm import:sefaria` last wrote there.
 */

export type KmChapterStatus =
  "imported" | "structure-unsupported" | "no-file-for-language";

export interface KmChapterOutcome {
  chapterId: string;
  status: KmChapterStatus;
  sourceSegments: number;
  commentaryItems: number;
  sourceItemsSkipped: number;
  commentaryParagraphsSkipped: number;
  unmatchedNumerals: number;
}

export interface KmLanguageOutcome {
  versionId: string;
  kmLanguage: string;
  title: string;
  chapters: KmChapterOutcome[];
  warnings: string[];
}

export const KM_COVERAGE_HEADING = "## KabbalahMedia import (`kabbalahmedia`)";

const languageTable = (languages: KmLanguageOutcome[]): string => {
  const header =
    "| Version | Language (KM code) | Chapters imported | Source segments | Commentary items |";
  const divider = "| --- | --- | --- | --- | --- |";
  const rows = languages.map((lang) => {
    const imported = lang.chapters.filter((c) => c.status === "imported");
    const segments = imported.reduce((sum, c) => sum + c.sourceSegments, 0);
    const commentary = imported.reduce((sum, c) => sum + c.commentaryItems, 0);
    return `| ${lang.versionId} | ${lang.title} (\`${lang.kmLanguage}\`) | ${imported.length}/${lang.chapters.length} | ${segments} | ${commentary} |`;
  });
  return [header, divider, ...rows].join("\n");
};

const skippedChapterNotes = (languages: KmLanguageOutcome[]): string[] =>
  languages
    .flatMap((lang) =>
      lang.chapters
        .filter((c) => c.status !== "imported")
        .map(
          (c) =>
            `- **${lang.versionId}**/${c.chapterId}: ${c.status === "structure-unsupported" ? "document structure not yet supported by this importer" : "no docx file for this language"}`,
        ),
    )
    .sort();

const warningNotes = (languages: KmLanguageOutcome[]): string[] =>
  languages.flatMap((lang) =>
    lang.warnings.map((w) => `- **${lang.versionId}**: ${w}`),
  );

/** Builds this run's KabbalahMedia section body (everything after the `## ` heading line). */
export const buildKmCoverageSection = (
  languages: KmLanguageOutcome[],
): string => {
  const lines = [
    "Generated by `pnpm import:kabbalahmedia`. Per language version: how many",
    "of Part 1 chapters 1-2 were imported, and how many total segments/",
    "commentary items were written. A language whose KabbalahMedia document",
    "doesn't (yet) match the structure this importer parses is listed as",
    "skipped, not force-imported.",
    "",
    languageTable(languages),
  ];

  const skipped = skippedChapterNotes(languages);
  if (skipped.length > 0) {
    lines.push("", "**Skipped chapters:**", ...skipped);
  }

  const warnings = warningNotes(languages);
  if (warnings.length > 0) {
    lines.push("", "**Warnings:**", ...warnings);
  }

  return lines.join("\n");
};

/**
 * Replaces the section starting at `heading` (up to the next top-level `## `
 * heading, or end of file) in `existing` with `heading` + `sectionBody`, or
 * appends it if `heading` isn't present yet. Pure string surgery — lets two
 * independent importers (Sefaria, KabbalahMedia) each own their own section
 * of the same `content/COVERAGE.md` without clobbering the other's.
 */
export const mergeMarkdownSection = (
  existing: string,
  heading: string,
  sectionBody: string,
): string => {
  const newSection = `${heading}\n\n${sectionBody}`.trimEnd();
  const headingIndex = existing.indexOf(`${heading}\n`);

  if (headingIndex === -1) {
    const before = existing.trimEnd();
    return before.length > 0
      ? `${before}\n\n${newSection}\n`
      : `${newSection}\n`;
  }

  const afterHeadingStart = headingIndex + heading.length;
  const rest = existing.slice(afterHeadingStart);
  const nextHeadingMatch = rest.match(/\n(?=## )/);
  const sectionEnd = nextHeadingMatch
    ? afterHeadingStart + (nextHeadingMatch.index as number) + 1
    : existing.length;

  const before = existing.slice(0, headingIndex).trimEnd();
  const after = existing.slice(sectionEnd).trimEnd();

  const parts = [before, newSection, after].filter((part) => part.length > 0);
  return `${parts.join("\n\n")}\n`;
};
