/**
 * The `@nuxt/fonts` provider that serves the fonts vendored into this
 * repository, so a production build makes no font requests at all (issue
 * #121).
 *
 * It is deliberately thin. Everything `@nuxt/fonts` does — generating the
 * `@font-face` CSS, the local-fallback metric rules, the preload hints, the
 * per-page subsetting decisions — keeps happening exactly as before. The only
 * thing that changed is where the face data comes from: `fonts.manifest.json`
 * on disk instead of `fonts.googleapis.com` over the network.
 *
 * The manifest is generated by `pnpm fonts:vendor` (`scripts/vendor-fonts.ts`)
 * from a build that DID fetch from Google, so it is a recording of the real
 * provider's output rather than a second guess at it. Never hand-edit it.
 *
 * A provider is just a function returning `{ resolveFont }` — no import from
 * `unifont` (a transitive dependency) is needed, and none is taken.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/** Repo-relative, so both the generator and `nuxt.config.ts` name it once. */
export const VENDORED_FONTS_MANIFEST = "fonts.manifest.json";

export interface VendoredFontFace {
  weight: string;
  style: string;
  unicodeRange: string;
  /** Site-absolute path under `public/`, e.g. `/fonts/david-libre-hebrew.woff2`. */
  src: string;
}

export interface VendoredFontsManifest {
  generatedBy: string;
  families: Record<string, VendoredFontFace[]>;
}

const readManifest = (): VendoredFontsManifest => {
  const path = fileURLToPath(
    new URL(`../../${VENDORED_FONTS_MANIFEST}`, import.meta.url),
  );
  return JSON.parse(readFileSync(path, "utf8")) as VendoredFontsManifest;
};

/**
 * `families` in the shape `nuxt.config.ts` wants: every family the manifest
 * covers, pointed at this provider. Derived rather than repeated, so a family
 * can never be vendored and left unregistered, or registered and unvendored.
 *
 * `fallbacks` are carried explicitly because a vendored family has no
 * upstream metadata saying whether it is a serif or a sans, and without them
 * the module would generate every family's fallback metrics against the
 * sans-serif defaults — silently, and wrongly for the three reading faces.
 */
export const vendoredFontFamilies = (
  fallbacksByFamily: Record<string, string[]>,
) =>
  Object.keys(readManifest().families).map((name) => ({
    name,
    provider: "vendored",
    fallbacks: fallbacksByFamily[name],
  }));

/**
 * A `unifont` provider FACTORY: calling it returns the provider, and calling
 * that returns the `{ resolveFont }` the module uses. `_name`/`_options` are
 * how `unifont` identifies a provider — `defineFontProvider` exists only to
 * attach them, and since `unifont` is a transitive dependency they are
 * attached here rather than imported.
 *
 * Getting this shape wrong does not error. The module resolves no faces, the
 * build succeeds, and the site ships with no `@font-face` rules at all — the
 * exact silent failure `scripts/verify-font-output.mjs` exists to catch,
 * which is why `task check` now runs it too and not just the deploy workflow.
 */
export const vendoredFontProvider = (options: Record<string, unknown> = {}) =>
  Object.assign(
    () => {
      const manifest = readManifest();

      return {
        resolveFont: (family: string) => {
          const faces = manifest.families[family];
          if (!faces) return undefined;

          return {
            fonts: faces.map((face) => ({
              src: [{ url: face.src, format: "woff2" }],
              weight: face.weight,
              style: face.style,
              unicodeRange: face.unicodeRange
                .split(",")
                .map((range) => range.trim()),
            })),
          };
        },
      };
    },
    { _name: "vendored" as const, _options: options },
  );
